apiVersion: batch/v1beta1
kind: CronJob
metadata:
   name: cronjob
spec:
   schedule: “*/1 * * * *”
   jobTemplate:
      spec:
         template:
            spec:
            containers:
            -  name: hello-world
               image: busybox
               command: [“echo”, “hello kubernetes job”]
            restartPolicy: OnFailure
