apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8s-pv
spec: 
  capacity: 
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  nfs:
    path: /data/volumes/v1
    server: 192.168.100.139
