apiVersion: v1
kind: Pod
metadata:
    name: myweb-pod
    labels: 
        name: myweb
spec:
    containers:
    - name: myweb
      image: tomcat
      ports:
        - containerPort: 8080
      env:
        - name: MYSQL_SERVICE_HOST
          value: mysql
        - name: MYSQL_SERVICE_PORT
          value: '3306'
