apiVersion: v1
kind: Pod
metadata: 
  name: nginx-hostpath
spec:
  containers:
  - name: web-nginx
    image: nginx
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
  volumes:
    - name: html
      hostPath:
        path: /data/pod/nginx
        type: DirectoryOrCreate
