apiVersion: apps/v1
kind: Deployment
metadata:
   name: nginx-webapp-update
spec:
   replicas: 1
   selector:
      matchLabels:
         app: nginx-webserver
   template:
      metadata:
         labels:
            app: nginx-webserver
      spec:
         containers:
         -  name: nginx
            image: nginx:1.9.1
