apiVersion: v1
kind: Pod
metadata:
  name: pod-pvc
spec:
  containers:
  - name: pod-pvc
    image: busybox
    args:
    -  /bin/sh
    - -c
    - sleep 30000
    volumeMounts:
    - mountPath: "/pvcdata"
      name: pvcdata
  volumes:
  - name: pvcdata
    persistentVolumeClaim:
      claimName: k8s-pvc
